### PR TITLE
Adds TJ The Translator Recipe

### PR DESCRIPTION
**Pull request by modcarroll**

### CODE REVIEW

**Comment by jweisz** [comment]
@modcarroll I'm confused... it looks like this is just duplicating `chat_with_tj` but hasn't implemented the translation functionality yet. Is it too soon to merge this, then?

**Comment by modcarroll** [comment]
@jweisz it essentially is the same recipe except the prompt is modified to instruct the model to perform the translation based on what the user says plus the language that they specify in the toml file. Maybe we should just combine them?

**Comment by jweisz** [comment]
@modcarroll Oh OK, I see it now. I was thrown off by the README saying "Chat with TJ". 🤷

**Comment by jweisz** [comment]
@modcarroll I just made a few README updates. But now I'm wondering if we want to change the script a little bit so that the first thing TJBot does is ask the user what language they want to translate to, and THEN start the translation process. Good idea?

**Comment by modcarroll** [comment]
> @modcarroll I just made a few README updates. But now I'm wondering if we want to change the script a little bit so that the first thing TJBot does is ask the user what language they want to translate to, and THEN start the translation process. Good idea?

Great idea! I'll add that

**Comment by modcarroll** [comment]
@jweisz take a look at the new flow - we can chat more about it on our call too!

**Review by jweisz — APPROVED** [review]

**Pull request merged**
